abstract class EyewitnessVisualizerStates {}

class EyewitnessVisualizerInitialState extends EyewitnessVisualizerStates{}

class EyewitnessVisualizerChangeBottomNavState extends EyewitnessVisualizerStates{}